name: Build-Java-11-Arclight
on: workflow_dispatch         # manual “Run workflow” button
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Fetch the source
      - uses: actions/checkout@v4

      # 2) Use Temurin 11 to compile (class-file 55)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      # 3) Build the shaded plugin jar
      - name: Gradle → shadowJar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean shadowJar
          gradle-version: wrapper  # use the project’s wrapper

      # 4) Upload the finished jar so you can grab it
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: RoseLoot-Arclight-Java11
          path: build/libs/*arclight*.jar
