name: Build-Java-11-Arclight
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    # 1) Install Temurin 11 and set JAVA_HOME
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "11"

    # 2) Build the shaded jar with the wrapper
    - name: Run Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean shadowJar      # plain shell, no extra build action

    # 3) Upload the finished jar
    - uses: actions/upload-artifact@v3
      with:
        name: RoseLoot-Arclight-Java11
        path: build/libs/*arclight*.jar
